### ISSUE TITLE
Runtime errors using BigWig files.

### ISSUE THREAD

**Issue by Carldeboer** [bxlab/bx-python#12]
I installed the latest bx-python version (0.8.0) on both python 3.3 and 2.7 and both got errors, but different errors, when opening (3.3) and retrieving data from (2.7) BigWig files.
Any ideas are greatly appreciated!

Python3.3:
```
Traceback (most recent call last):
  File "/home/unix/cgdeboer/bin/aggregateGenomeData.py", line 91, in <module>
    inFile1 = **BigWigFile(open(args.inFile))**
  File "bigwig_file.pyx", line 127, in bx.bbi.bigwig_file.BigWigFile.__init__ (lib/bx/bbi/bigwig_file.c:3437)
  File "bbi_file.pyx", line 119, in bx.bbi.bbi_file.BBIFile.__init__ (lib/bx/bbi/bbi_file.c:4404)
  File "bbi_file.pyx", line 129, in bx.bbi.bbi_file.BBIFile.open (lib/bx/bbi/bbi_file.c:4581)
  File "/home/unix/cgdeboer/.local/lib/python3.3/site-packages/bx_python-0.8.0-py3.3-linux-x86_64.egg/bx/misc/binary_file.py", line 37, in __init__
    bytes = file.read( 4 )
  File "/home/unix/cgdeboer/Python-3.3.3/lib/python3.3/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)
```

Python 2.7:
```
Traceback (most recent call last):
  File "/home/unix/cgdeboer/bin/aggregateGenomeData.py", line 125, in <module>
    values = **inFile1.get_as_array( locus[GENOMEDATA.CHR], stF, enF )**
  File "bigwig_file.pyx", line 153, in bx.bbi.bigwig_file.BigWigFile.get_as_array (lib/bx/bbi/bigwig_file.c:3795)
  File "bigwig_file.pyx", line 159, in bx.bbi.bigwig_file.BigWigFile.get_as_array (lib/bx/bbi/bigwig_file.c:3578)
  File "bbi_file.pyx", line 248, in bx.bbi.bbi_file.BBIFile._get_chrom_id_and_size (lib/bx/bbi/bbi_file.c:5656)
  File "bpt_file.pyx", line 76, in bx.bbi.bpt_file.BPTFile.find (lib/bx/bbi/bpt_file.c:1388)
  File "bpt_file.pyx", line 55, in bx.bbi.bpt_file.BPTFile.r_find (lib/bx/bbi/bpt_file.c:1154)
AttributeError: 'BinaryFileReader' object has no attribute 'read_bits64'
```

**Comment by Carldeboer** [comment]
Any ideas?

**Comment by rsharris** [comment]
(I'm not a recently active contributor to this package, where "recent" is at decade resolution)

My best guess at the python3 problem is that the file wasn't opened in binary mode.  So file.read thinks it's got a text file and decided to sanity check it for ascii compliance.  The default for file.open is text mode.  Not clear whether line 91 in aggregateGenomeData.py has "rb" as one of its arguments.

At one time there was no difference between text and binary files on *nix machines.  I wonder if that's still true.  Looking at https://docs.python.org/3/tutorial/inputoutput.html , the only difference I see mentioned is the usual windows vs *nix line endings.

That's just a guess though.  Interested to know if I'm right.

**Comment by jxtx** [comment]
We've really not tested on python 3. Should work on 2, I have not had a
chance to try yet.

**Comment by Carldeboer** [comment]
Is there a chance this could be an install issue?  A previous version worked, but I was having a problem where data from chr6 was missing and so upgraded.  Deleting the newer version seemed to have broken the old.  Copying the old version back to the lib dir and deleting the newer versions resulted in a similar error.

**Comment by jxtx** [comment]
Seems quite possible since the Travis tests (always a clean install) pass.
Is installing from bioconda an option?

**Comment by Carldeboer** [comment]
Looks like it was indeed a bad install. It works now, but unfortunately the bug I was hoping was fixed in the latest version remains so I will open a new ticket.

**Comment by jxtx** [comment]
Thanks Carl.


-- jt
