### ISSUE TITLE
Error building bx-python for python-2.7.13

### ISSUE THREAD

**Issue by wesbarris** [bxlab/bx-python#18]
Using either pip or manually building bx-python results in the same error.  This install is being attempted on a fresh install of python-2.7.13 on a CentOS 7.3 system.

> /usr/local/bin/python2.7 setup.py build
running build
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 233, in <module>
    main()
  File "setup.py", line 50, in main
    cmdclass=command_classes )
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Distutils/old_build_ext.py", line 203, in cython_sources
    from Cython.Compiler.Main \
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 30, in <module>
    from .Symtab import ModuleScope
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Compiler/Symtab.py", line 18, in <module>
    from . import PyrexTypes
  File "/usr/local/lib/python2.7/site-packages/Cython-0.25.2-py2.7-linux-x86_64.egg/Cython/Compiler/PyrexTypes.py", line 17, in <module>
    from .Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Cython/Compiler/Code.py", line 838, in init Cython.Compiler.Code (/usr/local/src/python/Cython-0.25.2/Cython/Compiler/Code.c:81208)
  File "/usr/local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

**Comment by mulchchristina** [comment]
Im having a similar problem, Im installing with conda and then adding the dir for bx-python to my path but the software im using refuses to see it...thoughts?

**Comment by nsoranzo** [comment]
@wesbarris This seems a problem with the Cython installation, not bx-python.

@mulchchristina There is already a bx-python package from bioconda, no need to compile it.
