### ISSUE TITLE
OverflowError: value too large to convert to int

### ISSUE THREAD

**Issue by peterch405** [bxlab/bx-python#21]
I am still having this issue:

Issue from: https://bitbucket.org/james_taylor/bx-python/issues/51/max-value-of-interval

```
from bx.intervals.intersection import IntervalTree
b = IntervalTree()
b.add(300000000,300000100,"a")
b.find(300000010,300000011)
>>>['a']
b.add(2119513096, 2234682974,"b")
>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "intersection.pyx", line 388, in bx.intervals.intersection.IntervalTree.insert (lib/bx/intervals/intersection.c:4823)
OverflowError: value too large to convert to int
```

**Comment by jxtx** [comment]
Definitely still an issue. Requires substantial changes to move from 32 to 64 bit.
