### ISSUE TITLE
Failed to load seekbzip2 module when dealing with bz2 files

### ISSUE THREAD

**Issue by songtaogui** [bxlab/bx-python#71]
Hi,

I have installed bx-python through `pip install` using python 2.7, the whole install step seems fine, and when dealing with unzipped maf files, everything works good. 

However, when I tried to dealing with bz2 compressed maf files, I have got this error msg:
```python
# my cmd:
# > maf_extract_ranges_indexed.py ref.maf.bz2 <test_region.bed
Traceback (most recent call last):
  File "/usr/local/bin/maf_extract_ranges_indexed.py", line 123, in <module>
    main()
  File "/usr/local/bin/maf_extract_ranges_indexed.py", line 67, in main
    index = bx.align.maf.MultiIndexed(maf_files, keep_open=True, parse_e_rows=True, use_cache=use_cache)
  File "/usr/local/lib/python2.7/dist-packages/bx/interval_index_file.py", line 175, in __init__
    for fname in filenames]
  File "/usr/local/lib/python2.7/dist-packages/bx/interval_index_file.py", line 178, in new_indexed_access
    return self.indexed_access_class(data_filename, index_filename, keep_open, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bx/interval_index_file.py", line 205, in __init__
    raise Exception("Trying to open .bz2 file but no seekbzip2 module found")
Exception: Trying to open .bz2 file but no seekbzip2 module found
```
I have already tried this action on another machine and it do work fine #69 .

So how could I solve this error ? 

Any suggestion would be grateful.

Best,

Songtao Gui

**Comment by nsoranzo** [comment]
@songtaogui Sorry, we decided to drop support for Python 2.7 as it is also unsupported upstream.
